-- Execute este script no SQL Editor do Supabase.

create extension if not exists "pgcrypto";

create table if not exists public.transactions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  description text not null,
  amount numeric(12,2) not null check (amount > 0),
  date date not null,
  type text not null check (type in ('income', 'expense')),
  category text not null,
  source_bank text not null default 'Manual',
  import_hash text,
  import_batch_id uuid,
  import_source_format text,
  imported_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.transactions add column if not exists source_bank text not null default 'Manual';
alter table public.transactions add column if not exists import_hash text;
alter table public.transactions add column if not exists import_batch_id uuid;
alter table public.transactions add column if not exists import_source_format text;
alter table public.transactions add column if not exists imported_at timestamptz;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'transactions_source_bank_length'
      and conrelid = 'public.transactions'::regclass
  ) then
    alter table public.transactions
      add constraint transactions_source_bank_length check (char_length(source_bank) <= 40);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'transactions_category_length'
      and conrelid = 'public.transactions'::regclass
  ) then
    alter table public.transactions
      add constraint transactions_category_length check (char_length(category) <= 60);
  end if;
end
$$;

create table if not exists public.goals (
  user_id uuid primary key references auth.users(id) on delete cascade,
  expense_limit numeric(12,2) not null default 0,
  savings_goal numeric(12,2) not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  unique (user_id, name)
);

create table if not exists public.category_budgets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  category_name text not null,
  budget_amount numeric(12,2) not null check (budget_amount >= 0),
  updated_at timestamptz not null default now(),
  unique (user_id, category_name)
);

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists idx_transactions_user_date
on public.transactions (user_id, date desc);

create unique index if not exists idx_transactions_user_import_hash
on public.transactions (user_id, import_hash)
where import_hash is not null;

create index if not exists idx_transactions_user_import_batch
on public.transactions (user_id, import_batch_id)
where import_batch_id is not null;

create index if not exists idx_categories_user_name
on public.categories (user_id, name);

create index if not exists idx_category_budgets_user_category
on public.category_budgets (user_id, category_name);

create index if not exists idx_usage_events_user_created
on public.usage_events (user_id, created_at desc);

alter table public.transactions enable row level security;
alter table public.goals enable row level security;
alter table public.categories enable row level security;
alter table public.category_budgets enable row level security;
alter table public.usage_events enable row level security;

drop policy if exists "transactions_select_own" on public.transactions;
drop policy if exists "transactions_insert_own" on public.transactions;
drop policy if exists "transactions_update_own" on public.transactions;
drop policy if exists "transactions_delete_own" on public.transactions;
drop policy if exists "goals_select_own" on public.goals;
drop policy if exists "goals_insert_own" on public.goals;
drop policy if exists "goals_update_own" on public.goals;
drop policy if exists "categories_select_own" on public.categories;
drop policy if exists "categories_insert_own" on public.categories;
drop policy if exists "categories_update_own" on public.categories;
drop policy if exists "categories_delete_own" on public.categories;
drop policy if exists "category_budgets_select_own" on public.category_budgets;
drop policy if exists "category_budgets_insert_own" on public.category_budgets;
drop policy if exists "category_budgets_update_own" on public.category_budgets;
drop policy if exists "category_budgets_delete_own" on public.category_budgets;
drop policy if exists "usage_events_select_own" on public.usage_events;
drop policy if exists "usage_events_insert_own" on public.usage_events;

create policy "transactions_select_own"
on public.transactions
for select
using (auth.uid() = user_id);

create policy "transactions_insert_own"
on public.transactions
for insert
with check (auth.uid() = user_id);

create policy "transactions_update_own"
on public.transactions
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "transactions_delete_own"
on public.transactions
for delete
using (auth.uid() = user_id);

create policy "goals_select_own"
on public.goals
for select
using (auth.uid() = user_id);

create policy "goals_insert_own"
on public.goals
for insert
with check (auth.uid() = user_id);

create policy "goals_update_own"
on public.goals
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "categories_select_own"
on public.categories
for select
using (auth.uid() = user_id);

create policy "categories_insert_own"
on public.categories
for insert
with check (auth.uid() = user_id);

create policy "categories_update_own"
on public.categories
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "categories_delete_own"
on public.categories
for delete
using (auth.uid() = user_id);

create policy "category_budgets_select_own"
on public.category_budgets
for select
using (auth.uid() = user_id);

create policy "category_budgets_insert_own"
on public.category_budgets
for insert
with check (auth.uid() = user_id);

create policy "category_budgets_update_own"
on public.category_budgets
for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "category_budgets_delete_own"
on public.category_budgets
for delete
using (auth.uid() = user_id);

create policy "usage_events_select_own"
on public.usage_events
for select
using (auth.uid() = user_id);

create policy "usage_events_insert_own"
on public.usage_events
for insert
with check (auth.uid() = user_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_goals_set_updated_at on public.goals;
create trigger trg_goals_set_updated_at
before update on public.goals
for each row
execute function public.set_updated_at();

drop trigger if exists trg_category_budgets_set_updated_at on public.category_budgets;
create trigger trg_category_budgets_set_updated_at
before update on public.category_budgets
for each row
execute function public.set_updated_at();
